export const ECONOMIC_FLIGHT_FETCH_SUCCEEDED = 'FLIGHT_FETCH_SUCCEEDED';
export const BUSINESS_FLIGHT_FETCH_SUCCEEDED = 'BUSINESS_FLIGHT_FETCH_SUCCEEDED';
export const ECONOMIC_FLIGHT_FETCH = 'FIGHT_FETCH_REQUESTED';
export const BUSINESS_FLIGHT_FETCH = 'BUSINESS_FLIGHT_FETCH';